### ISSUE TITLE
URL in install message is missing path

### ISSUE THREAD

**Issue by eeeple** [YunoHost-Apps/bitwarden_ynh#65]
Hi,

There's an issue with the post-install email not containing the path to the app, only the domain

> Please open https://domain.tld/admin

When it should say :

> Please open https://domain.tld/app_path/admin

Below is an example of the email i received post installation.

```
This is an automated message from your beloved YunoHost server.

Specific information for the application bitwarden.

Bitwarden was successfully installed :)
Please open https://domain.tld/admin
The admin token is:
REDACTEDREDACTEDREDACTEDREDACTEDREDACTEDREDACTEDREDACTEDREDACTED
You will be able to invit users to your bitwarden instance.
If you facing an issue or want to improve this app, please open a new issue in this project: https://github.com/YunoHost-Apps/bitwarden_ynh

---
Automatic diagnosis data from YunoHost

host: Debian 9.12
kernel: 4.4.114-mainline-rev1
packages: 
  yunohost: 
    repo: stable
    version: 3.7.1.1
  yunohost-admin: 
    repo: stable
    version: 3.7.1.1
  moulinette: 
    repo: stable
    version: 3.7.1
  ssowat: 
    repo: stable
    version: 3.7.1.1
backports: 
system: 
  disks: 
    vda: Mounted on /, 45.7GiB (31.6GiB free)
  memory: 
    ram: 2.0GiB (945.8MiB free)
    swap: 0B (0B free)
nginx: 
  - nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
  - nginx: configuration file /etc/nginx/nginx.conf test is successful
```
